## Exercícios Aulas 1 a 4
Prof Roger Rendón

In [30]:
#Imports
import numpy as np
import pandas as pd
import random

#### Numpy.

In [7]:
#1. Gere uma array randomica de 10 elementos com duas dimensões, e explore o array (ndim, dtype e shape). 
array_randomico = np.random.randint(0,10,size=(2,5))
print(array_randomico.ndim)
print(array_randomico.dtype)
print(array_randomico.shape)
print(array_randomico.size)
print(array_randomico)
print(type(array_randomico))

2
int32
(2, 5)
10
[[5 3 0 5 7]
 [2 8 7 3 7]]
<class 'numpy.ndarray'>


In [13]:
#2. Verifique os elementos da array e veja se tem valores NaN e transforme os valores NaN pra número
arr2 =  np.array([1, 0, np.nan, 6.0])
where_is_nan = np.isnan(arr2)
arr2[where_is_nan] = 0
arr2

array([1., 0., 0., 6.])

In [17]:
#3. Gere duas arrays de uma dimensão com 10 elementos cada, valores entre 1 e 50. 
    # Faça comparações entre as duas matrizes ( >, <, equal)

array_randomico2 = np.random.randint(1,50,size=(10))
array_randomico3 = np.random.randint(1,50,size=(10))

g_than = array_randomico2 > array_randomico3
g_than
print(array_randomico2)
print(array_randomico3)
print(array_randomico2[g_than])

[41  7 17 11 43 47 17 12 48 25]
[20 15 46 27 27 26 43 19 26 26]
[41 43 47 48]


In [3]:
#4. Faça uma array com aragne de 12 elementos e de o reshape correto nele. 
    # Salve sua array em um arquivo de texto (Dica = Save Text and Headers)
arr3 = np.arange(1,24,2)
arr4 = np.reshape(arr3,(3,-1))
np.savetxt(fname= 'arquivo_teste.npy', X=arr4, header= 'arquivo de teste numpy', delimiter=';', fmt= '%.0f')

In [29]:
#5. Carregue o arquvio da array anterior e faça uma subseleções:
    #Elemento na linha 1 coluna 1 
    #Elementos na coluna 2
    #Elementos na linha 2 e escolha o maximo valor dessa seleção
    #Uma array nova com o resultado de uma seleção complexa ex. (arr1 > 3) & (arr1 % 2 == 0)
from matplotlib.pyplot import axes


array_teste = np.loadtxt(fname='arquivo_teste.npy',delimiter = ';')
elemento11 = array_teste[0][0]
elemento_2 = array_teste[:,1]
elemento_max2 = array_teste[1].max()
array_novo = array_teste[(array_teste > 10) & (array_teste < 20)]
array_novo

    

array([11., 13., 15., 17., 19.])

In [71]:
#6. Gere duas arrays em formato de matriz e faça um dot product nela 
matriz1= np.matrix(np.random.randint(0,5,size=(2,2)))
matriz2= np.matrix(np.random.randint(5,10,size=(2,2)))

print(matriz1,'\n\n', matriz2, '\n')

dot_product = matriz1*matriz2
print(dot_product)

[[3 0]
 [1 3]] 

 [[6 9]
 [9 6]] 

[[18 27]
 [33 27]]


#### Pandas

In [ ]:
#1. Faça uma pandas Series com valores inteiros randomicos de tamanho 30 de numeros entre 5 e 15
    # Divida sua serie em duas partes e gere duas series novas 
    # Adicione 5 valores a cada serie e mantenha os dois elementos como series
    # Conte as aparições de cada elemento da Serie
    # Faça comparações booleanas entre as das series
    # Junte as duas series em um dataframe
    # Rename nas colunas utilizando inplace 
    # Explore seu novo DataFrame


In [98]:
serie1 = pd.Series(np.random.randint(5,16,size=30))
serie2 = pd.Series(serie1[int(np.size(serie1)/2):].copy())
serie1 = serie1[:int(np.size(serie1)/2)]

serie3=pd.Series([1,2,3,4,5])
serie1 = serie1.append(serie3).reset_index(drop= True)
serie2 = serie2.append(serie3).reset_index(drop= True)
print(serie1, serie2)

0      5
1      9
2      5
3     15
4     14
5      6
6     15
7      7
8      5
9      5
10    10
11    13
12    15
13    10
14    15
15     1
16     2
17     3
18     4
19     5
dtype: int64 0      7
1     15
2      7
3     12
4      6
5     15
6      5
7     11
8      9
9     15
10     5
11    10
12     8
13     7
14    15
15     1
16     2
17     3
18     4
19     5
dtype: int64


In [91]:
serie1.value_counts()

15    3
14    3
11    3
5     2
13    1
12    1
10    1
9     1
8     1
1     1
2     1
3     1
4     1
dtype: int64

In [106]:
df_1 = pd.DataFrame({'serie1':serie1,'serie2':serie2})
df_1

serie1  serie2
0        5       7
1        9      15
2        5       7
3       15      12
4       14       6
5        6      15
6       15       5
7        7      11
8        5       9
9        5      15
10      10       5
11      13      10
12      15       8
13      10       7
14      15      15
15       1       1
16       2       2
17       3       3
18       4       4
19       5       5

In [ ]:
#2. Carregue o dataset da url (https://www.kaggle.com/datasets/andrewmvd/global-monkeypox-cases)
    # Explore seu dataframe
    # Faça uma lista com todas as colunas disponíveis 
    # Veja todos os paises que tem no dataframe
    # Faça um groupby pais e veja quantos casos tem cada pais, gere um novo df com essa informação
    # Faça um groupby por status e pais e veja quantos casos confirmados tem por pais


In [ ]:
#3 Opcional(vamos discutir em aula)
    # O que vocês fariam com a coluna Idade?
    
    # Faça o tratamento de acordo com a sua linha de pensamento
    
    # Esse tratamento que fez é útil (Sim / Não e Por que)?
    
    # O que podemos fazer com essa informação para ter um dado mais acertivo?