<div>
<img src="Imgs/logo-numpy.svg" width="250"/>
</div>

https://numpy.org

- Abreviação para Numerical Python
- É base para muitos outros pacotes, inclusive pacotes de Machinle Learning 
- Utilizado para computação de alta performance 
- Utilizado para analise e transformação de dados
- É utilizado frequentemente em conjunto com Pandas (Próximo tema)

Curiosidade sobre Numpy
https://numpy.org/case-studies/blackhole-image/

In [3]:
import numpy as np

#### Conceitos principais

In [ ]:
#numpy.ndarray VS Lists
list1 = [4,2,5,6,10]
array1 = np.array(list1)
print(f'List: {list1}')
print(type(list1))
print(list1)
print(type(list1[1]))
print(type(list1[4]))
print('\n')
print(f'Numpy array: {array1}')
print(f'Type: {type(array1)}')
print(array1)
print(type(array1[0]))
print(type(array1[3]))


In [ ]:
# Soma de um numero na lista e no nparray
arr + 2

In [ ]:
list1 + 2

>Todos os itens de um array devem ser do mesmo tipo, diferentemente os itens de uma lista. Segue!

- i - integer
- b - boolean
- U - unsigned integer (Inteiros que não tem simbolos de + ou - associados )
- f - float
- c - complex float (Numeros Imaginarios)
- m - timedelta
- M - datetime
- O - object
- S - string
- U - unicode string

In [ ]:
#Testes com diferentes tipos
#Str>Float>Int
list2 = [[2,3,4,4],[3,40,100,0]]

In [ ]:
#dtype param 


In [ ]:
#ndim, shape, size, dtype


In [ ]:
#astype


In [ ]:
#zeros = array feita de zeros

#ones - array feita de qualquer numero

#empty - array dada um tamanho e tipo determinado com valores randomicos

#full - parecida a ones porem mais "elegante"

#fulllike - cria um array baseada em uma existente com outro numero dado

# arange - cria um array com elementos separados por um step

#copias do array 


#### Operações entre ndarrays

> Numpy foi feito para manipular e realizar operações vetorizadas em grande escala, com velocidade

In [ ]:
#creating random arrays  = np.random.random_sample retorna array do tamanho pedido com numeros entre 0.0, 1.0

In [ ]:
np.random.random_sample((3, 3))

In [ ]:
#multipy, divide, add, subtract


##### DIY

Ex 1
1) Transforme a duas listas em duas arrays diferentes arr1 e arr2.
2) Verifique o dtype dos array
3) Transforme os dois array em float
4) Compare as duas arrays e mostre os indices dos elementos que são iguais(dica : where)
5) Retorne os numeros do array que são iguais usando o output do paso 4 dica subsetting

In [20]:
list_1 = [1,2,3,4,5]
list_2 = [1,3,2.2,4,5]

In [26]:
array1 = np.array(list_1)
array2 = np.array(list_2)

print(array1.dtype)
print(array2.dtype)

#array1 = array1.astype(float)
array2 = array2.astype(float)

np.where(array1==array2)

array1[np.where(array1==array2)]

int32
float64


C:\Users\grego\AppData\Local\Temp\ipykernel_17992\1952002342.py:12: FutureWarning: Using a non-tuple sequence for multidimensional indexing is deprecated; use `arr[tuple(seq)]` instead of `arr[seq]`. In the future this will be interpreted as an array index, `arr[np.array(seq)]`, which will result either in an error or a different result.
  array1[[np.where(array1==array2)]]


array([[1, 4, 5]])

#### Indexação, Slicing

In [27]:
array = np.array([[1, 2, 3, 4, 5, 6, 7], [8, 9, 10, 11, 12, 13, 14]])
array

array([[ 1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14]])

In [ ]:
#seleção por index [linha, coluna]
#numero especifico
 
#numero especifico negativo


# : é chamado de slicing [startindex:endindex:stepsize]
#primera linha

#todos os elementos da 2 coluna

#elemento especificos com step


> conseguimos mudar também elementos especificos de uma array usando index e slicing

In [ ]:
#trocando um numero especifico
array[1,:] = 87
#trocar coluna inteira 

#voltar os valores originais 


#### DIY

Ex 2
1) Gere uma array com 3 dimensões com shape. (2,2,2)
2) Printe o ndim da array e o shape
3) Retire um elemento especifico [bloco][linha][coluna]



In [1]:
array3d= np.random.random_sample((2,2,2))

NameError: name 'np' is not defined

In [65]:
#print array
array3d

array([[[0.86407842, 0.05237822],
        [0.00236041, 0.78070719]],

       [[0.07465605, 0.71547064],
        [0.39110778, 0.76986218]]])

In [47]:
#print ndim
array3d.ndim

3

In [48]:
#print shape
array3d.shape

(2, 2, 2)

In [71]:
#print elemento
print(np.resize(array3d[0,0],(2,1)))
print('')
print(array3d)


[[0.86407842]
 [0.05237822]]

[[[0.86407842 0.05237822]
  [0.00236041 0.78070719]]

 [[0.07465605 0.71547064]
  [0.39110778 0.76986218]]]


##### Dica

O array 3D é um conjunto de arrays de duas dimensões, "um array de arrays de arrays", os elementos são acessados para um indice para linha, um para coluna um para o bloco ( Parecido com um cubo). Tem apliações em diversas areas como: Jogos, Data Wharehouses, Analise de dados entre outros. 

Ordem [bloco][linha][coluna]

<div>
<img src="Imgs/arrays.png" width="500"/>
</div>
<img src="Imgs/formato3d.png" width="500"/>

#### Transposição, Stacking e Redimensionamento

<img src="Imgs/transpose.png" width="500"/>

In [58]:
array = np.array([[1, 2, 3, 4, 5, 6, 7], [8, 9, 10, 11, 12, 13, 14]])
array

array([[ 1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14]])

In [57]:
array.T

array([[ 1,  8],
       [ 2,  9],
       [ 3, 10],
       [ 4, 11],
       [ 5, 12],
       [ 6, 13],
       [ 7, 14]])

#### Estatistica

In [78]:
stats = np.random.random_sample((2,3))
stats

array([[0.56067713, 0.03931724, 0.06235952],
       [0.4901772 , 0.84920363, 0.82807394]])

In [79]:
#minimo do nosso array
np.min(stats)

0.039317235831947905

In [80]:
#maximo do nosso array
np.max(stats)

0.8492036269750028

In [84]:
#minima por linha
np.min(stats, axis=1)

array([0.03931724, 0.4901772 ])

In [85]:
#minima por coluna
np.min(stats, axis=0)

array([0.4901772 , 0.03931724, 0.06235952])

In [90]:
#maximo de uma coluna especifica
np.min(stats[:,0], axis=0)
np.min(stats[0])

0.039317235831947905

In [96]:
stats[0,:]
np.min(stats[0,:], axis=0)

0.039317235831947905

#### DIY - Grupos

https://archive.ics.uci.edu/ml/datasets/Wine+Quality

In [98]:
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/wine-quality/winequality-red.csv'

DICA : Procure por nan e substitua por 0 (dica: is_nan e nan_to_num)m

https://numpy.org/devdocs/user/basics.io.genfromtxt.html
1) Verifique a url e veja quais são as colunas do arquivo
2) Veja qual é o delimiter do arquivo ',' , ':', ';'
3) Selecione as colunas (param usecols) Citric Acid, PH e  Alcohol
4) Mostre o array e as caracteristicas dele ndim, shape, dype
5) Procure o maximo e minimo da coluna PH 
6) Obtenha a media da coluna Alcohol

In [142]:
#Import data
wine_arr = np.genfromtxt(url,delimiter=';', usecols= [2,8,10])

In [122]:
#Show array
print(wine_arr)

print(wine_arr.ndim)

print(wine_arr.shape)

print(wine_arr.dtype)


[[  nan   nan   nan]
 [ 0.    3.51  9.4 ]
 [ 0.    3.2   9.8 ]
 ...
 [ 0.13  3.42 11.  ]
 [ 0.12  3.57 10.2 ]
 [ 0.47  3.39 11.  ]]
2
(1600, 3)
float64


In [144]:
# array_sem_nan = np.where(not np.isnan(wine_arr.any()))
# wine_arr = np.nan_to_num(wine_arr)
wine_arr = wine_arr[1:,:]
wine_arr

array([[ 0.  ,  3.51,  9.4 ],
       [ 0.  ,  3.2 ,  9.8 ],
       [ 0.04,  3.26,  9.8 ],
       ...,
       [ 0.13,  3.42, 11.  ],
       [ 0.12,  3.57, 10.2 ],
       [ 0.47,  3.39, 11.  ]])

In [145]:
#Max e Min
print(np.max(wine_arr))
print(np.min(wine_arr))

14.9
0.0


In [146]:
#Mean
print(np.mean(wine_arr))

4.668357306649989


#### Extra

1) Faça um for loop que itere por todos os elementos de uma array de 3 dimensões

In [126]:
array_3d= np.array(([[1,2],[3,4]],[[5,6],[7,8]]))

for bloco in array_3d:
    for linha in bloco:
        for elemento in linha:
            print(elemento)
print(array_3d)

1
2
3
4
5
6
7
8
[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]
